# Generated by Django 3.0.3 on 2020-08-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='balance',
            table='balance',
        ),
    ]
