# Generated by Django 3.0.3 on 2020-09-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200828_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='deleted',
            new_name='status',
        ),
    ]
