# Generated by Django 3.0.3 on 2020-07-05 21:30

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('user_client', models.IntegerField(blank=True, null=True)),
                ('post_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('post_media_type', models.IntegerField(blank=True, null=True)),
                ('post_media_urls', jsonfield.fields.JSONField(blank=True, null=True)),
                ('post_like_num', models.IntegerField(blank=True, null=True)),
                ('post_share_num', models.IntegerField(blank=True, null=True)),
                ('deleted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
    ]
