# Generated by Django 3.0.3 on 2020-07-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailPageAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'managed': True},
        ),
    ]
